const { test, before, after, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
require('./offlineNetwork.cjs');
Object.assign(process.env, { NODE_ENV: 'test', JWT_SECRET: 'synthetic-7g-offline-auth', PAYMENTS_MODE: 'disabled', PAYMENTS_PROVIDER: 'none' });
const express = require('express');
const jwt = require('jsonwebtoken');
const { createRouter } = require('../routes/adminReconciliation');
const { createTestRepository } = require('./helpers/inMemoryReconciliationRepository.cjs');
const { evaluate } = require('../services/paymentReconciliation');
const operations = require('../services/reconciliationOperationsReadModel');
let repo, server, base, calls, writes;
const admin = jwt.sign({ id: 1, role: 'admin' }, process.env.JWT_SECRET, { expiresIn: '1h' });
const user = jwt.sign({ id: 2, role: 'user' }, process.env.JWT_SECRET, { expiresIn: '1h' });
const decision = (requestId = 'a'.repeat(32)) => evaluate({ intent: { state: 'PAYMENT_INTENT_READY', reviewState: 'REVIEW_READY', requestId, amount: '10.00', currency: 'EUR' }, provider: 'synthetic_mock', providerPaymentId: 'synthetic_payment', paymentState: 'PAYMENT_OUTCOME_UNKNOWN', booking: { state: 'BOOKING_CONFIRMED', providerResultObserved: true } });
const seed = async id => { const result = decision(id); await repo.upsertCase({ result, evidence: null, expectedVersion: 0, observedAt: '2026-10-08T10:00:00.000Z' }); return operations.projectCase(result); };
const request = async (path = '', token = admin, method = 'GET', namespace = '/fixture/reconciliation') => {
  const response = await fetch(base + namespace + path, { method, headers: token ? { Authorization: `Bearer ${token}` } : {} });
  const text = await response.text(); return { status: response.status, data: text ? JSON.parse(text) : null, allow: response.headers.get('allow') };
};
before(async () => {
  const app = express();
  app.use('/api/admin/reconciliation', createRouter());
  const delegate = { upsertCase() { writes++; assert.fail('HTTP write'); }, getCaseById: id => repo.getCaseById(id), findByCorrelation: id => repo.findByCorrelation(id), listCases: () => repo.listCases() };
  app.use('/fixture/reconciliation', createRouter({ repository: delegate }));
  server = app.listen(0, '127.0.0.1'); await new Promise(resolve => server.once('listening', resolve)); base = `http://127.0.0.1:${server.address().port}`;
});
after(async () => { server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); });
beforeEach(t => {
  repo = createTestRepository(); calls = writes = 0;
  const forbidden = () => { calls++; assert.fail('DB/provider/operator operation'); };
  for (const name of ['query', 'connect']) t.mock.method(require('../db'), name, forbidden);
  for (const name of ['availability', 'checkRates', 'createBooking', 'cancelBooking', 'getBooking', 'listBookings']) t.mock.method(require('../integrations/hotelbeds/client'), name, forbidden);
  for (const name of ['confirm', 'cancel', 'simulateCancellation', 'reconcile']) t.mock.method(require('../services/hotelbedsBookingService'), name, forbidden);
  t.mock.method(require('../services/paymentGatewayService'), 'createIntent', forbidden);
  for (const name of ['requestSandboxRefund', 'completeSandboxRefund']) t.mock.method(require('../controllers/refundController'), name, forbidden);
  for (const name of ['recordAction', 'safeRecordAction']) t.mock.method(require('../services/adminAuditService'), name, forbidden);
  for (const name of ['info', 'warn', 'error']) t.mock.method(require('../utils/logger'), name, forbidden);
});
afterEach(() => { assert.equal(calls, 0); assert.equal(writes, 0); });
test('guest denied', async () => assert.equal((await request('', null)).status, 401));
test('normal user denied', async () => assert.equal((await request('', user)).status, 403));
test('invalid JWT denied', async () => assert.equal((await request('', 'invalid')).status, 401));
test('admin allowed', async () => assert.equal((await request()).status, 200));
test('default source truthfully unavailable with no cases', async () => assert.deepEqual((await request('', admin, 'GET', '/api/admin/reconciliation')).data, { source: 'unavailable', code: 'RECONCILIATION_SOURCE_UNAVAILABLE', items: [], pagination: { page: 1, limit: 25, total: 0, pages: 1 } }));
test('default detail is safe 404', async () => assert.deepEqual(await request('/' + 'a'.repeat(64), admin, 'GET', '/api/admin/reconciliation'), { status: 404, data: { code: 'RECONCILIATION_CASE_NOT_FOUND' }, allow: null }));
test('available empty differs from disabled', async () => { const r = await request(); assert.equal(r.data.source, 'available'); assert.deepEqual(r.data.items, []); });
test('list returns exact existing safe projection', async () => { const row = await seed(); assert.deepEqual((await request()).data.items, operations.list([decision()]).items); assert.equal((await request()).data.items[0].caseId, row.caseId); });
test('detail returns exact safe projection and timeline', async () => { const row = await seed(); assert.deepEqual((await request('/' + row.caseId)).data, operations.detail([decision()], row.caseId)); });
test('missing detail is explicit 404', async () => assert.equal((await request('/' + 'f'.repeat(64))).status, 404));
test('family identity reads same detail', async () => { const row = await seed(); assert.equal((await request('/' + row.caseFamilyId)).data.caseFamilyId, row.caseFamilyId); });
test('raw evidence secrets PII and storage internals never serialized', async () => {
  const result = decision(), row = operations.projectCase(result), marker = 'private-sensitive-marker';
  const record = { snapshots: [{ result: { ...result, rawWebhook: marker, email: marker, diagnostic: { ...result.diagnostic, signature: marker } } }], evidence: [{ Authorization: marker, card: marker, passport: marker }], version: 99, dbUrl: marker };
  repo = { listCases: async () => ({ source: 'available', records: [record] }), getCaseById: async () => ({ source: 'available', record }) };
  for (const path of ['', '/' + row.caseId]) { const r = await request(path); assert.equal(r.status, 200); assert.doesNotMatch(JSON.stringify(r.data), /private-sensitive-marker|rawWebhook|signature|Authorization|passport|version|snapshots|dbUrl/); }
});
test('priority category and status filters select safely', async () => { const row = await seed(); for (const key of ['priority', 'category', 'status']) { assert.equal((await request('?' + key + '=' + row[key])).data.items.length, 1); } assert.equal((await request('?priority=LOW')).data.items.length, 0); });
test('boolean filters preserve false', async () => { await seed(); assert.equal((await request('?manualReviewRequired=true&compensationRequired=false')).data.items.length, 1); assert.equal((await request('?manualReviewRequired=false')).data.items.length, 0); });
test('unknown and SQL-like sorting rejected', async () => { for (const q of ['sort=version', 'priority=HIGH%3BDROP', 'providerFingerprint=abc']) assert.equal((await request('?' + q)).status, 400); });
test('invalid enums rejected', async () => { for (const q of ['priority=urgent', 'category=PAID', 'status=RESOLVED']) assert.equal((await request('?' + q)).status, 400); });
test('arrays and invalid booleans rejected', async () => { for (const q of ['priority=HIGH&priority=LOW', 'manualReviewRequired=1', 'compensationRequired=FALSE']) assert.equal((await request('?' + q)).status, 400); });
test('pagination validates positive integer and max100', async () => { for (const q of ['page=0', 'page=1.5', 'limit=101', 'limit=-1', 'page=100001']) assert.equal((await request('?' + q)).status, 400); assert.equal((await request('?limit=100')).status, 200); });
test('pagination applied after deterministic family projection', async () => { await seed('b'.repeat(32)); await seed('a'.repeat(32)); const all = (await request()).data.items; const page = (await request('?page=2&limit=1')).data; assert.deepEqual(page.items, [all[1]]); assert.deepEqual(page.pagination, { page: 2, limit: 1, total: 2, pages: 2 }); });
test('insertion order does not change list ordering', async () => { await seed('b'.repeat(32)); await seed('a'.repeat(32)); const a = (await request()).data.items; repo = createTestRepository(); await seed('a'.repeat(32)); await seed('b'.repeat(32)); assert.deepEqual((await request()).data.items, a); });
test('malformed identity and detail queries rejected', async () => { for (const p of ['/bad', '/' + 'A'.repeat(64), '/' + 'a'.repeat(64) + '?raw=true']) assert.equal((await request(p)).status, 400); });
test('repository exceptions are fixed safe errors', async () => { repo = { listCases: async () => { throw Error('private-sensitive-marker'); }, getCaseById: async () => { throw Error('private-sensitive-marker'); } }; for (const p of ['', '/' + 'a'.repeat(64)]) { const r = await request(p); assert.equal(r.status, 503); assert.deepEqual(r.data, { code: 'RECONCILIATION_SOURCE_UNAVAILABLE' }); } });
test('malformed and excessive source fails closed', async () => { for (const records of [{}, Array(1001).fill({}), [{ snapshots: [{ result: {} }] }]]) { repo = { listCases: async () => ({ source: 'available', records }) }; assert.equal((await request()).status, 503); } });
test('unavailable source cannot smuggle records', async () => { repo = { listCases: async () => ({ source: 'unavailable', records: [{ snapshots: [{ result: decision() }] }] }) }; assert.equal((await request()).status, 503); });
for (const method of ['POST', 'PUT', 'PATCH', 'DELETE']) test(method + ' unavailable with no writes or operator calls', async () => { const r = await request('', admin, method); assert.equal(r.status, 405); assert.equal(r.allow, 'GET'); });
test('unknown descendant cannot fall through to admin mutations', async () => assert.equal((await request('/' + 'a'.repeat(64) + '/resolve')).status, 404));
test('production registration uses guarded router and disabled default', () => { const source = require('node:fs').readFileSync(require.resolve('../routes/adminOperations'), 'utf8'); assert.match(source, /router\.use\('\/reconciliation', require\('\.\/adminReconciliation'\)\.createRouter\(\)\)/); });
