const { test, beforeEach } = require('node:test');
const assert = require('node:assert/strict');
const jwt = require('jsonwebtoken'), bcrypt = require('bcryptjs'), pool = require('../db');
const upgrade = require('../services/legacyPasswordUpgrade'), controller = require('../controllers/authController');
const secret = require('node:crypto').randomBytes(32).toString('hex');
const res = () => ({ statusCode: 200, status(n) { this.statusCode=n; return this; }, json(body) { this.body=body; return this; } });
let row, queries, writes, hashes, race, dbError;
beforeEach(t => {
  const old = { JWT_SECRET:process.env.JWT_SECRET, SESSION_STATE_ENFORCEMENT:process.env.SESSION_STATE_ENFORCEMENT };
  process.env.JWT_SECRET=secret; process.env.SESSION_STATE_ENFORCEMENT='enabled';
  t.after(()=>{for(const k of Object.keys(old)) { if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k]; }});
  row={id:1,role:'user',is_active:true,session_version:1,password:'SYNTHETIC_HASH',email:'synthetic@example.test',full_name:'Synthetic'};
  queries=writes=hashes=0;race=dbError=false;
  t.mock.method(pool,'query',async(sql,values)=>{queries++;if(dbError)throw Error('PRIVATE_DATABASE');if(sql.startsWith('SELECT'))return{rows:row?[{...row}]:[]};writes++;assert.match(sql,/session_version = session_version \+ 1/);assert.match(sql,/password = \$3/);if(race)return{rows:[]};if(row.session_version!==values[3])return{rows:[]};row.password=values[0];row.session_version++;return{rows:[{id:1}]};});
  t.mock.method(bcrypt,'hash',async(value,cost)=>{assert.equal(cost,12);hashes++;return 'SYNTHETIC_NEW_HASH';});
  const fail=()=>assert.fail('FORBIDDEN_IO_OR_LOG');
  for(const C of [require('pg').Pool,require('pg').Client]) for(const k of ['connect','query'])t.mock.method(C.prototype,k,fail);
  for(const p of ['http','https'])for(const k of ['get','request'])t.mock.method(require(p),k,fail);
  t.mock.method(require('node:net').Socket.prototype,'connect',fail);
  for(const k of ['info','warn','error'])t.mock.method(require('../utils/logger'),k,fail);
});
const sign=(patch={},options={})=>jwt.sign({type:'legacy_password_update',id:1,sessionVersion:1,...patch},secret,{algorithm:'HS256',expiresIn:300,...options});
async function update(token,password='new-password',extra={}){if(arguments.length===0)token=upgrade.issue(row);const reply=res();await upgrade.update({body:{passwordUpdateToken:token,newPassword:password,...extra}},reply);return reply;}
test('issue has exact purpose, HS256 and300secondTTL without role',()=>{const token=upgrade.issue(row),d=jwt.decode(token,{complete:true});assert.equal(d.header.alg,'HS256');assert.equal(d.payload.type,'legacy_password_update');assert.equal(d.payload.exp-d.payload.iat,300);assert.equal(d.payload.role,undefined);});
for(const token of [null,undefined,'','malformed',{},'x'.repeat(4097)])test(`invalid input category ${typeof token}/${String(token).length} before DB`,async()=>{assert.equal((await update(token)).statusCode,401);assert.equal(queries,0);});
for(const patch of [{type:'normal'},{type:'travio_provider_offer'},{type:undefined},{role:'admin'},{id:0},{id:1.5},{sessionVersion:0},{sessionVersion:1.5},{sessionVersion:2147483647}])test(`wrong claim ${Object.keys(patch)[0]} ${String(Object.values(patch)[0])}`,async()=>{assert.equal((await update(sign(patch))).statusCode,401);assert.equal(queries,0);});
test('HS384 capability rejected',async()=>{assert.equal((await update(sign({}, {algorithm:'HS384'}))).statusCode,401);assert.equal(queries,0);});
test('expired capability rejected before DB',async()=>{assert.equal((await update(sign({}, {expiresIn:-1}))).statusCode,401);assert.equal(queries,0);});
test('excessive expiry rejected',async()=>assert.equal((await update(sign({}, {expiresIn:3600}))).statusCode,401));
test('tampered signature rejected',async()=>{const token=sign();assert.equal((await update(token.slice(0,-5)+'abcde')).statusCode,401);});
test('normal session JWT rejected as upgrade',async()=>{assert.equal((await update(jwt.sign({id:1,role:'admin',sessionVersion:1},secret,{expiresIn:300}))).statusCode,401);assert.equal(queries,0);});
test('upgrade rejected by normal auth before account query',async()=>{let next=0;const reply=res();await require('../middleware/authMiddleware')({get:()=>`Bearer ${sign()}`},reply,()=>next++);assert.equal(reply.statusCode,401);assert.equal(next,0);assert.equal(queries,0);});
test('upgrade rejected by offer verifier even if signing keys match in synthetic dev',()=>{const old=process.env.OFFER_TOKEN_SECRET;process.env.OFFER_TOKEN_SECRET=secret;try{assert.throws(()=>require('../services/offerTokenService').verify(sign()));}finally{if(old===undefined)delete process.env.OFFER_TOKEN_SECRET;else process.env.OFFER_TOKEN_SECRET=old;}});
for(const mode of ['inactive','deleted','version'])test(`current account ${mode} blocked`,async()=>{const token=sign();if(mode==='inactive')row.is_active=false;if(mode==='deleted')row=null;if(mode==='version')row.session_version=2;assert.equal((await update(token)).statusCode,401);assert.equal(hashes,0);});
for(const password of ['a'.repeat(73),'é'.repeat(37),'short',{},null])test(`new password boundary ${typeof password}/${String(password).length}`,async()=>{assert.equal((await update(sign(),password)).statusCode,400);assert.equal(queries,0);});
test('query-only token does not authenticate',async()=>{const reply=res();await upgrade.update({query:{passwordUpdateToken:sign()},body:{newPassword:'new-password'}},reply);assert.equal(reply.statusCode,401);assert.equal(queries,0);});
test('unknown body fields rejected',async()=>{assert.equal((await update(sign(),'new-password',{role:'admin'})).statusCode,400);assert.equal(queries,0);});
test('successful replacement increments version and replay fails',async()=>{const token=sign(),reply=await update(token);assert.deepEqual(reply.body,{code:'PASSWORD_UPDATED',reauthenticationRequired:true});assert.equal(row.session_version,2);assert.equal(writes,1);assert.equal(hashes,1);assert.equal((await update(token)).statusCode,401);assert.equal(writes,1);});
test('concurrent update race does not report success',async()=>{race=true;assert.equal((await update()).statusCode,401);assert.equal(row.session_version,1);});
test('DB failure fixed503 without raw error',async()=>{dbError=true;assert.deepEqual((await update()).body,{code:'PASSWORD_UPDATE_UNAVAILABLE'});});
test('old auth session stale after upgrade',async()=>{const session={id:1,role:'user',sessionVersion:1};await update();assert.equal(await require('../services/accountSecurityState').authenticate(session),null);});
test('fresh ordinary login after replacement issues current session',async t=>{await update();t.mock.method(bcrypt,'compare',async()=>true);const reply=res();await controller.login({body:{email:row.email,password:'new-password'}},reply);assert.equal(reply.statusCode,200);assert.equal(jwt.verify(reply.body.token,secret).sessionVersion,2);});
test('legacy login only issues purpose capability after verified compare',async t=>{t.mock.method(bcrypt,'compare',async()=>true);const reply=res();await controller.login({body:{email:row.email,password:'a'.repeat(80)}},reply);assert.equal(reply.statusCode,409);assert.equal(reply.body.token,undefined);assert.equal(upgrade.verify(reply.body.passwordUpdateToken).id,1);assert.equal(writes,0);});
test('route inherits auth/API buckets and has no session middleware requirement',()=>{const fs=require('node:fs');const server=fs.readFileSync(require('node:path').resolve(__dirname,'../server.js'),'utf8');assert.match(server,/app.use\("\/api\/auth", authRateLimiter, authRoutes\)/);assert.match(server,/app.use\("\/api", apiRateLimiter\)/);assert.ok(require('../routes/auth').stack.some(x=>x.route?.path==='/legacy-password-update'));});
