const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const sql = fs.readFileSync(path.resolve(__dirname, '../../database/migrations/021_reconciliation_storage.sql'), 'utf8');
test('next numbered additive SQL migration', () => assert.ok(fs.existsSync(path.resolve(__dirname, '../../database/migrations/020_catalog_environment_identity.sql'))));
test('only two justified tables', () => assert.deepEqual([...sql.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/g)].map(m => m[1]), ['reconciliation_cases', 'reconciliation_observations']));
test('stable correlation primary key', () => assert.match(sql, /case_family_id TEXT PRIMARY KEY/));
test('composite unique correlation identity', () => assert.match(sql, /UNIQUE \(request_id, provider_fingerprint, payment_fingerprint\)/));
test('immutable evaluator alias primary key', () => assert.match(sql, /observation_id TEXT PRIMARY KEY/));
test('provider event identity unique globally', () => assert.match(sql, /UNIQUE \(provider_fingerprint, event_fingerprint\)/));
test('composite FK binds exact owning correlation', () => assert.match(sql, /FOREIGN KEY \(case_family_id, request_id, provider_fingerprint, payment_fingerprint\)/));
test('positive optimistic version', () => assert.match(sql, /CHECK \(version >= 1\)/));
test('safe integer observed money and ISO currency', () => { assert.match(sql, /amount_minor > 0 AND amount_minor <= 9007199254740991/); assert.match(sql, /currency ~ '\^\[A-Z\]\{3\}\$'/); });
test('event-free observations distinct from complete normalized evidence', () => { assert.match(sql, /event_fingerprint IS NULL AND evidence_digest IS NULL/); assert.match(sql, /reconciled IS NOT NULL/); });
test('UTC observation/database timestamps', () => { assert.match(sql, /first_observed_at TIMESTAMPTZ/); assert.match(sql, /updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW\(\)/); });
test('bounded query patterns indexed without blanket JSON GIN', () => { assert.match(sql, /case_family_id, observed_at, observation_id/); assert.match(sql, /reconciliation_cases_status_idx/); assert.match(sql, /reconciliation_cases_category_idx/); assert.doesNotMatch(sql, /USING GIN/); });
test('no raw webhook secret card or PII columns', () => assert.doesNotMatch(sql, /\b(rawBody|raw_webhook|signature|authorization|api_key|jwt|offer_token|card_number|cvv|passport|traveller_dob)\b/i));
test('no destructive statement or unrelated mutation', () => assert.doesNotMatch(sql, /\b(DROP|TRUNCATE|DELETE|UPDATE|ALTER|INSERT)\s+(TABLE|INTO|\w+)/i));
test('no invented intent money or lifecycle columns', () => { const cases = sql.split('CREATE TABLE IF NOT EXISTS reconciliation_observations')[0]; assert.doesNotMatch(cases, /amount_minor|currency|lifecycle_status/); });
test('runner owns transaction and has no down migration convention', () => { const runner = fs.readFileSync(path.resolve(__dirname, '../scripts/migrate.js'), 'utf8'); assert.match(runner, /filter\(\(file\) => file.endsWith\("\.sql"\)\)/); assert.match(runner, /query\("BEGIN"\)/); assert.doesNotMatch(sql, /^BEGIN;|^COMMIT;/m); });
