import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
const require = createRequire(import.meta.url);
require('../../backend/tests/offlineNetwork.cjs');
const { evaluate } = require('../../backend/services/paymentReconciliation');
const operations = require('../../backend/services/reconciliationOperationsReadModel');
test('7G authenticated read API integration offline', async t => {
  const server = await createServer({ root: fileURLToPath(new URL('..', import.meta.url)), configFile: false, server: { middlewareMode: true, hmr: false }, esbuild: { jsx: 'automatic' } });
  const old = { storage: globalThis.localStorage, window: globalThis.window }, memory = new Map();
  globalThis.localStorage = { getItem: key => memory.get(key) ?? null, setItem: (key, value) => memory.set(key, value), removeItem: key => memory.delete(key) };
  globalThis.window = new EventTarget(); window.location = { href: '/' };
  let requests = [], response = { source: 'unavailable', items: [], pagination: { page: 1, limit: 100, total: 0, pages: 1 } }, status = 200;
  t.mock.method(globalThis, 'fetch', async (url, options) => { assert.match(url, /\/api\/admin\/reconciliation(?:\?|\/[a-f0-9]{64}$)/); assert.equal(options.method, 'GET'); assert.equal(options.body, undefined); requests.push({ url, options }); return { ok: status < 400, status, text: async () => JSON.stringify(response) }; });
  try {
    const service = await server.ssrLoadModule('/src/services/reconciliationService.js');
    const stores = await server.ssrLoadModule('/src/services/reconciliationStore.js');
    const session = await server.ssrLoadModule('/src/services/session.js');
    const { ReconciliationView } = await server.ssrLoadModule('/src/components/admin/ReconciliationCenter.jsx');
    const decision = evaluate({ intent: { state: 'PAYMENT_INTENT_READY', reviewState: 'REVIEW_READY', requestId: 'a'.repeat(32), amount: '10.00', currency: 'EUR' }, provider: 'synthetic_mock', providerPaymentId: 'synthetic_payment', paymentState: 'PAYMENT_OUTCOME_UNKNOWN', booking: { state: 'BOOKING_CONFIRMED', providerResultObserved: true } });
    const row = operations.list([decision]).items[0], detail = operations.detail([decision], row.caseId);
    const login = role => { session.logout(); session.establishSession('synthetic_session', { id: 1, role }, session.beginAuthAttempt()); };
    const store = () => stores.createReconciliationStore();
    const html = s => renderToStaticMarkup(React.createElement(ReconciliationView, { state: s.getSnapshot(), actions: s }));
    const reset = () => { login('admin'); requests = []; status = 200; response = { source: 'unavailable', items: [] }; };
    const run = (name, fn) => t.test(name, async () => { reset(); await fn(); });
    await run('list uses bounded authenticated GET', async () => { await service.readReconciliationList(); assert.match(requests[0].url, /\/admin\/reconciliation\?page=1&limit=100$/); assert.equal(requests[0].options.headers.Authorization, 'Bearer synthetic_session'); });
    await run('detail uses exact validated case URL', async () => { response = detail; assert.deepEqual(await service.readReconciliationDetail(row.caseId), detail); assert.ok(requests[0].url.endsWith('/' + row.caseId)); });
    await run('priority encoded safely', async () => { await service.readReconciliationList({ priority: 'HIGH' }); assert.match(requests[0].url, /priority=HIGH/); });
    await run('category and status encoded safely', async () => { await service.readReconciliationList({ category: row.category, status: row.status }); const q = new URL(requests[0].url, 'http://local').searchParams; assert.equal(q.get('category'), row.category); assert.equal(q.get('status'), row.status); });
    await run('boolean false preserved', async () => { await service.readReconciliationList({ manualReviewRequired: true, compensationRequired: false }); assert.match(requests[0].url, /manualReviewRequired=true&compensationRequired=false/); });
    await run('empty UI filter omitted', async () => { await service.readReconciliationList({ priority: '' }); assert.doesNotMatch(requests[0].url, /priority=/); });
    await run('unknown filters cannot reach transport', () => { assert.throws(() => service.readReconciliationList({ sort: 'version' })); assert.equal(requests.length, 0); });
    await run('injected enum value rejected', () => { assert.throws(() => service.readReconciliationList({ priority: 'HIGH&raw=true' })); assert.equal(requests.length, 0); });
    await run('nonboolean filter rejected', () => { assert.throws(() => service.readReconciliationList({ manualReviewRequired: 'true' })); assert.equal(requests.length, 0); });
    await run('path escaping case rejected', () => { for (const id of ['../refund', row.caseId + '?raw=true', 'A'.repeat(64), null]) assert.throws(() => service.readReconciliationDetail(id)); assert.equal(requests.length, 0); });
    await run('unavailable API renders truthful state with no fake rows', async () => { const s = store(); await s.load(); assert.equal(s.getSnapshot().status, 'unavailable'); assert.match(html(s), /Источник данных сверки пока не подключён/); assert.doesNotMatch(html(s), /<table>/); });
    await run('available empty is distinct', async () => { response = { source: 'available', items: [] }; const s = store(); await s.load(); assert.equal(s.getSnapshot().status, 'empty'); assert.match(html(s), /Нет случаев для проверки/); });
    await run('admin loads safe API rows', async () => { response = { source: 'available', items: [row] }; const s = store(); await s.load(); assert.equal(s.getSnapshot().items.length, 1); assert.match(html(s), /<table>/); });
    await run('normal user denied before GET', async () => { login('user'); const s = store(); await s.load(); assert.equal(s.getSnapshot().status, 'denied'); assert.equal(requests.length, 0); });
    await run('guest denied before GET', async () => { session.logout(); const s = store(); await s.load(); assert.equal(s.getSnapshot().status, 'denied'); assert.equal(requests.length, 0); });
    await run('403 gives denied state', async () => { status = 403; response = { code: 'FORBIDDEN' }; const s = store(); await s.load(); assert.equal(s.getSnapshot().status, 'denied'); });
    await run('401 clears stale authenticated session', async () => { status = 401; await assert.rejects(service.readReconciliationList(), { status: 401 }); assert.equal(memory.get('token'), undefined); });
    await run('repository error hides raw text', async () => { status = 503; response = { message: 'private-sensitive-marker', stack: 'private-sensitive-marker' }; const s = store(); await s.load(); assert.equal(s.getSnapshot().status, 'error'); assert.doesNotMatch(html(s) + JSON.stringify(s.getSnapshot()), /private-sensitive-marker/); });
    await run('detail404 renders safe not-found', async () => { response = { source: 'available', items: [row] }; const s = store(); await s.load(); status = 404; response = { code: 'RECONCILIATION_CASE_NOT_FOUND' }; await s.open(row.caseId); assert.match(html(s), /Случай не найден/); });
    await run('raw webhook secrets and PII removed from API rendering', async () => { response = { source: 'available', items: [{ ...row, rawWebhook: 'private-sensitive-marker', Authorization: 'private-sensitive-marker', email: 'private-sensitive-marker' }] }; const s = store(); await s.load(); response = { ...detail, passport: 'private-sensitive-marker', signature: 'private-sensitive-marker' }; await s.open(row.caseId); assert.doesNotMatch(html(s) + JSON.stringify(s.getSnapshot()), /private-sensitive-marker|passport|signature|rawWebhook/); });
    await run('no refund cancel retry resolve action buttons', async () => { response = { source: 'available', items: [row] }; const s = store(); await s.load(); const buttons = html(s).match(/<button[^>]*>[\s\S]*?<\/button>/g)?.join(' ') || ''; assert.doesNotMatch(buttons, /Refund|Cancel|Retry|Resolved|Возврат|Отменить|Повторить|Завершить/); });
    await run('local filter does not issue mutation or extra request', async () => { response = { source: 'available', items: [row] }; const s = store(); await s.load(); s.filter('priority', 'LOW'); assert.equal(requests.length, 1); assert.equal(requests[0].options.method, 'GET'); });
  } finally { await server.close(); globalThis.localStorage = old.storage; globalThis.window = old.window; }
});
