import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createServer} from 'vite';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {MemoryRouter} from 'react-router-dom';

test('5C shared favorites and supported profile quality',async t=>{
 const server=await createServer({root:fileURLToPath(new URL('..',import.meta.url)),configFile:false,server:{middlewareMode:true,hmr:false},esbuild:{jsx:'automatic'}});
 const old={storage:globalThis.localStorage,window:globalThis.window};
 const memory=new Map([['token','user-a']]);
 globalThis.localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
 globalThis.window=new EventTarget();window.location={href:'/'};
 const hotel={provider:'hotelbeds',providerHotelId:'3424',name:'Grand Kaptan',city:'ALANYA',country:'Turkey',contentEnvironment:'test',stars:5};
 const user={id:7,full_name:'Анна',email:'fixture@example.test',phone:'123',role:'user',preferred_language:'ru',email_notifications:false,booking_reminders:false};
 let rows=[],fail=false,calls=[];
 t.mock.method(globalThis,'fetch',async(url,options={})=>{
   const path=new URL(url,'http://localhost').pathname.replace(/^\/api/,'');const method=options.method||'GET';
   assert.ok(path==='/favorites'||path==='/favorites/hotelbeds/3424','Only own favorites API permitted');calls.push([method,path]);
   if(fail)return {ok:false,status:500,text:async()=>JSON.stringify({message:'PRIVATE_SQL_TOKEN'})};
   if(method==='POST')rows=[hotel];if(method==='DELETE')rows=[];
   return {ok:true,status:200,text:async()=>JSON.stringify({success:true,data:method==='POST'?hotel:rows})};
 });
 try{
  const api=await server.ssrLoadModule('/src/services/savedAccountData.js');
  const {createAccountListStore}=await server.ssrLoadModule('/src/services/accountListStore.js');
  const {createProfileStore}=await server.ssrLoadModule('/src/services/profileStore.js');
  const {FavoritesView}=await server.ssrLoadModule('/src/pages/Favorites.jsx');
  const {ProfileView}=await server.ssrLoadModule('/src/pages/Profile.jsx');
  const p=await server.ssrLoadModule('/src/utils/profilePresentation.js');
  const session=await server.ssrLoadModule('/src/services/session.js');
  const render=el=>renderToStaticMarkup(React.createElement(MemoryRouter,{},el));
  const favorites=(state,extra={})=>render(React.createElement(FavoritesView,{favorites:state.items,status:state.status,pending:state.pending,...extra}));
  const fresh=(token='user-a')=>createAccountListStore({ownerToken:token,readToken:()=>memory.get('token'),loadData:api.readFavorites});
  const profile=(apiOverrides={})=>createProfileStore({token:'user-a',api:{getProfile:async()=>user,updateProfile:async data=>({user:{...user,...data}}),...apiOverrides}});
  const profileHtml=store=>render(React.createElement(ProfileView,{state:store.getSnapshot(),actions:store}));
  const source=path=>readFile(new URL('../src/'+path,import.meta.url),'utf8');
  await t.test('guest Favorites has login and register without requests',async()=>{const n=calls.length;const s=fresh(null);await s.load();assert.match(favorites(s.getSnapshot()),/Войдите|Войти/);assert.match(favorites(s.getSnapshot()),/Создать аккаунт/);assert.equal(calls.length,n);});
  await t.test('favorites loading is distinct',()=>assert.match(favorites(fresh().getSnapshot()),/Загружаем избранное/));
  await t.test('favorites empty has search CTA',async()=>{rows=[];const s=fresh();await s.load();assert.match(favorites(s.getSnapshot()),/В избранном пока ничего нет/);assert.match(favorites(s.getSnapshot()),/#home-search/);});
  await t.test('favorites error is safe',async()=>{fail=true;const s=fresh();await s.load();assert.match(favorites(s.getSnapshot()),/Не удалось загрузить избранное/);assert.doesNotMatch(favorites(s.getSnapshot()),/PRIVATE_SQL/);fail=false;});
  await t.test('favorites retry loads ready list',async()=>{fail=true;const s=fresh();await s.load();fail=false;rows=[hotel];await s.load();assert.match(favorites(s.getSnapshot()),/Grand Kaptan/);});
  await t.test('canonical identity ignores offer price and names',()=>{assert.equal(api.favoriteKey(hotel),api.favoriteKey({...hotel,price:999,name:'Different',roomName:'Other',id:123}));assert.notEqual(api.favoriteKey(hotel),api.favoriteKey({...hotel,provider:'mock'}));});
  await t.test('GET deduplicates numeric/string canonical ids',async()=>{rows=[hotel,{...hotel,providerHotelId:3424}];assert.equal((await api.readFavorites()).length,1);rows=[];});
  await t.test('add only after confirmation and remove share canonical store',async()=>{const s=fresh();await s.load();const add=api.toggleSavedFavorite(s,hotel);assert.equal(s.getSnapshot().items.length,0);await add;assert.equal(s.getSnapshot().items.length,1);await api.toggleSavedFavorite(s,{...hotel,price:999});assert.equal(s.getSnapshot().items.length,0);});
  await t.test('same-tick double click dispatches one mutation',async()=>{rows=[];const s=fresh();await s.load();const n=calls.length;await Promise.all([api.toggleSavedFavorite(s,hotel),api.toggleSavedFavorite(s,hotel)]);assert.equal(calls.length,n+1);assert.equal(s.getSnapshot().items.length,1);});
  await t.test('pending key visible and failed add preserves empty list',async()=>{rows=[];const s=fresh();await s.load();fail=true;const op=api.toggleSavedFavorite(s,hotel);assert.deepEqual(s.getSnapshot().pending,['hotelbeds:3424']);await assert.rejects(op);assert.equal(s.getSnapshot().items.length,0);assert.deepEqual(s.getSnapshot().pending,[]);fail=false;});
  await t.test('failed remove preserves saved hotel',async()=>{rows=[hotel];const s=fresh();await s.load();fail=true;await assert.rejects(api.toggleSavedFavorite(s,hotel));assert.equal(s.getSnapshot().items.length,1);fail=false;});
  await t.test('toggle waits for canonical load instead of blind POST',async()=>{rows=[hotel];const s=fresh();const n=calls.length;await api.toggleSavedFavorite(s,hotel);assert.deepEqual(calls.slice(n).map(x=>x[0]),['GET','DELETE']);});
  await t.test('failed initial load cannot mutate',async()=>{fail=true;const s=fresh();const n=calls.length;await assert.rejects(api.toggleSavedFavorite(s,hotel));assert.deepEqual(calls.slice(n).map(x=>x[0]),['GET']);fail=false;});
  await t.test('guest toggle never reaches protected mutation',async()=>{const n=calls.length;await assert.rejects(api.toggleSavedFavorite(fresh(null),hotel),/AUTH_REQUIRED/);assert.equal(calls.length,n);});
  await t.test('favorites invalidate clears data and pending',async()=>{rows=[hotel];const s=fresh();await s.load();s.invalidate();assert.deepEqual(s.getSnapshot().items,[]);assert.deepEqual(s.getSnapshot().pending,[]);});
  await t.test('new user never inherits old pending response',async()=>{let done;const s=createAccountListStore({ownerToken:'user-a',readToken:()=>memory.get('token'),loadData:()=>new Promise(r=>{done=r;})});const op=s.load();await Promise.resolve();s.invalidate();memory.set('token','user-b');done([hotel]);await op;assert.deepEqual(s.getSnapshot().items,[]);const b=fresh('user-b');assert.deepEqual(b.getSnapshot().items,[]);memory.set('token','user-a');});
  await t.test('ready cards are factual TEST hotel without fabricated live offer',()=>{const html=favorites({items:[hotel],status:'ready',pending:[]});assert.match(html,/Hotelbeds TEST/);assert.match(html,/без актуального предложения/);assert.doesNotMatch(html,/selectedOffer|\/tour\/|EUR|Бронировать/);assert.match(html,/aria-pressed="true"/);});
  await t.test('old prices explicitly historical',()=>{const html=favorites({items:[{...hotel,price:20,currency:'EUR'}],status:'ready',pending:[]});assert.match(html,/Последняя сохранённая цена/);assert.match(html,/Текущая стоимость может отличаться/);});
  await t.test('Results delegates favorite to TourCard shared context',async()=>{assert.match(await source('pages/Results.jsx'),/<TourCard/);assert.match(await source('components/TourCard.jsx'),/useFavorites/);assert.match(await source('components/TourCard.jsx'),/favoriteLock.current/);});
  await t.test('Details uses same context and repeated-click guard',async()=>{const s=await source('pages/TourDetails.jsx');assert.match(s,/useFavorites/);assert.match(s,/pendingFavorite/);assert.match(s,/aria-pressed=\{favoriteActive\}/);});
  await t.test('Favorites page and header consume same canonical list',async()=>{assert.match(await source('pages/Favorites.jsx'),/useFavorites/);assert.match(await source('components/Navbar.jsx'),/useFavorites/);});
  await t.test('profile guest has clear sign-in CTA',()=>{const s=createProfileStore({token:null});assert.match(profileHtml(s),/Войти/);assert.match(profileHtml(s),/Создать аккаунт/);});
  await t.test('profile loading contains no account data',()=>{assert.match(profileHtml(profile()),/Загружаем профиль/);assert.doesNotMatch(profileHtml(profile()),/fixture@example/);});
  await t.test('profile ready renders supported fields',async()=>{const s=profile();await s.load();const html=profileHtml(s);assert.match(html,/Анна/);assert.match(html,/profile-phone/);assert.doesNotMatch(html,/passport|birthDate|IIN/);});
  await t.test('validation rejects missing name and overlong supported fields',()=>{assert.ok(p.profileErrors({...p.profileDraft(user),full_name:'  '}).full_name);assert.ok(p.profileErrors({...p.profileDraft(user),phone:'x'.repeat(51)}).phone);});
  await t.test('save trims text using existing contract',async()=>{let body;const s=profile({updateProfile:async data=>{body=data;return {user:{...user,...data}};}});await s.load();s.edit('full_name','  New  ');s.edit('phone','  123  ');await s.save();assert.equal(body.full_name,'New');assert.equal(body.phone,'123');assert.equal(body.email,undefined);});
  await t.test('unchanged profile is not saved',async()=>{let count=0;const s=profile({updateProfile:async()=>{count++;}});await s.load();await s.save();assert.equal(count,0);assert.equal(s.getSnapshot().dirty,false);});
  await t.test('editing marks dirty and reset restores server snapshot',async()=>{const s=profile();await s.load();s.edit('full_name','Draft');assert.equal(s.getSnapshot().dirty,true);s.cancel();assert.equal(s.getSnapshot().draft.full_name,user.full_name);assert.equal(s.getSnapshot().dirty,false);});
  await t.test('save pending prevents duplicate submission and edits',async()=>{let done,count=0;const s=profile({updateProfile:()=>{count++;return new Promise(r=>{done=r;});}});await s.load();s.edit('full_name','Saved');const a=s.save();assert.equal(a,s.save());assert.equal(s.getSnapshot().saving,true);s.edit('full_name','Ignored');await Promise.resolve();assert.equal(count,1);done({user:{...user,full_name:'Saved'}});await a;assert.equal(s.getSnapshot().draft.full_name,'Saved');assert.equal(s.getSnapshot().saving,false);});
  await t.test('successful save becomes new reset baseline',async()=>{const s=profile();await s.load();s.edit('full_name','Saved');await s.save();assert.match(profileHtml(s),/Изменения сохранены/);s.edit('full_name','Another');s.cancel();assert.equal(s.getSnapshot().draft.full_name,'Saved');});
  await t.test('failed save preserves dirty draft with fixed message',async()=>{const s=profile({updateProfile:async()=>{throw Error('PRIVATE_SQL_TOKEN');}});await s.load();s.edit('full_name','Unsaved');await s.save();assert.equal(s.getSnapshot().dirty,true);assert.equal(s.getSnapshot().draft.full_name,'Unsaved');assert.match(profileHtml(s),/Не удалось сохранить изменения/);assert.doesNotMatch(profileHtml(s),/PRIVATE_SQL/);});
  await t.test('email remains read-only identity',async()=>{const s=profile();await s.load();s.edit('email','bad');assert.equal(s.getSnapshot().draft.email,undefined);assert.match(profileHtml(s),/id="profile-email"[^>]*readOnly/i);});
  await t.test('expired profile session clears data',async()=>{const s=profile({getProfile:async()=>{throw Object.assign(Error('private'),{status:401});}});await s.load();assert.equal(s.getSnapshot().status,'auth');assert.equal(s.getSnapshot().user,null);assert.equal(memory.has('token'),false);memory.set('token','user-a');});
  await t.test('profile invalidation clears all private and pending state',async()=>{const s=profile();await s.load();s.edit('full_name','Draft');s.editPassword('currentPassword','private');s.invalidate();assert.equal(s.getSnapshot().user,null);assert.equal(s.getSnapshot().draft,null);assert.equal(s.getSnapshot().password.currentPassword,'');assert.equal(s.getSnapshot().saving,false);});
  await t.test('late profile response cannot publish into next user',async()=>{let done;const s=profile({getProfile:()=>new Promise(r=>{done=r;})});const op=s.load();await Promise.resolve();memory.set('token','user-b');memory.set('user','new-user');done(user);await op;assert.equal(memory.get('user'),'new-user');assert.equal(s.getSnapshot().user,null);memory.set('token','user-a');});
  await t.test('logout clears session without network',()=>{const n=calls.length;session.logout();assert.equal(memory.has('token'),false);assert.equal(memory.has('user'),false);assert.equal(calls.length,n);memory.set('token','user-a');});
  await t.test('guest header and auth header retain semantic navigation',async()=>{const s=await source('components/Navbar.jsx');assert.match(s,/to="\/login"/);assert.match(s,/to="\/register"/);assert.match(s,/to="\/profile"/);assert.match(s,/onClick=\{logout\}/);assert.match(s,/accountName\(user\)/);});
  await t.test('responsive contracts cover narrow cards/profile/navbar',async()=>{const f=await source('styles/Favorites.css'),p=await source('styles/Profile.css'),n=await source('styles/Navbar.css');assert.match(f,/minmax\(0,1fr\)/);assert.match(f,/max-width:700px/);assert.match(p,/max-width:600px/);assert.match(n,/max-width:1040px/);assert.match(n,/overflow-y:auto/);});
  await t.test('a11y pending/status/labels and focus retained',async()=>{const s=profile();await s.load();assert.match(profileHtml(s),/aria-live="polite"/);assert.match(profileHtml(s),/readOnly/i);assert.match(await source('styles/AccountPages.css'),/:focus-visible/);assert.match(await source('components/TourCard.jsx'),/aria-pressed/);});
  await t.test('unicode lengths match PostgreSQL character limits',()=>{assert.deepEqual(p.profileErrors({...p.profileDraft(user),full_name:'\u{1f600}'.repeat(255),phone:'\u{1f600}'.repeat(50)}),{});assert.ok(p.profileErrors({...p.profileDraft(user),full_name:'\u{1f600}'.repeat(256)}).full_name);});
  await t.test('favorite controls remount on session switch without reloading Details',async()=>{assert.match(await source('components/TourCard.jsx'),/TourCardView key=\{favoriteSessionKey\}/);assert.match(await source('pages/TourDetails.jsx'),/DetailsFavoriteButton key=\{favoriteSessionKey\}/);assert.match(await source('context/FavoritesContext.jsx'),/favoriteSessionKey: token/);});
  await t.test('parallel list reads share one request',async()=>{const s=fresh();const n=calls.length;const first=s.load();assert.equal(first,s.load());await first;assert.equal(calls.length,n+1);});
  await t.test('new profile store starts empty and loads its own account',async()=>{memory.set('token','user-b');const b=createProfileStore({token:'user-b',api:{getProfile:async()=>({...user,id:8,full_name:'Second user'})}});assert.equal(b.getSnapshot().user,null);await b.load();assert.equal(b.getSnapshot().user.id,8);assert.equal(profileHtml(b).includes(user.full_name),false);memory.set('token','user-a');});
  await t.test('no provider network or raw UI errors',async()=>{assert.ok(calls.every(([,path])=>path.startsWith('/favorites')));for(const path of ['pages/Favorites.jsx','pages/Profile.jsx','components/SavedHotelCard.jsx'])assert.doesNotMatch(await source(path),/\{error\.message\}|dangerouslySetInnerHTML|checkRate|availability\(/);});
 }finally{globalThis.localStorage=old.storage;globalThis.window=old.window;await server.close();}
});
