import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { MemoryRouter } from 'react-router-dom';
import postcss from 'postcss';

test('5F consumer feedback offline contracts', async t => {
  const server = await createServer({root:fileURLToPath(new URL('..',import.meta.url)),configFile:false,server:{middlewareMode:true,hmr:false},esbuild:{jsx:'automatic'}});
  const previous = { storage:globalThis.localStorage, window:globalThis.window };
  const memory = new Map();
  globalThis.localStorage = {getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
  globalThis.window = new EventTarget(); window.location = {href:'/'};
  const requests = [];
  let status=200, body=[], wait=null;
  t.mock.method(globalThis,'fetch',async(url,options={})=>{
    const parsed=new URL(url,'http://localhost');
    assert.ok(['http://localhost','http://localhost:5000'].includes(parsed.origin),'external origin forbidden');
    const path=parsed.pathname.replace(/^\/api/,'');
    assert.ok(['/favorites','/favorites/mock/11','/bookings/me','/auth/login','/auth/register','/search'].includes(path),'unexpected API path');
    requests.push([path,options.method||'GET']);
    const code=status, result=body;
    if(wait) await wait.promise;
    return {ok:code===200,status:code,text:async()=>JSON.stringify(result),json:async()=>result};
  });
  const source=path=>readFile(new URL('../src/'+path,import.meta.url),'utf8');
  const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {resolve,promise};};
  const render=(C,props={})=>renderToStaticMarkup(React.createElement(MemoryRouter,{},React.createElement(C,props)));
  const poison='PRIVATE_SQL stack https://internal.invalid/secret Authorization password';
  const safe=html=>assert.doesNotMatch(html,/PRIVATE_SQL|internal\.invalid|Authorization|stack/);
  const user={id:7,full_name:'Fixture',email:'fixture@example.test',role:'user'};
  const hotel={id:11,provider:'mock',name:'Saved hotel'};
  try {
    const {FavoritesView}=await server.ssrLoadModule('/src/pages/Favorites.jsx');
    const {ProfileView}=await server.ssrLoadModule('/src/pages/Profile.jsx');
    const {MyBookingsView}=await server.ssrLoadModule('/src/pages/MyBookings.jsx');
    const {BookingDetailsView}=await server.ssrLoadModule('/src/pages/BookingDetails.jsx');
    const {AccountError,AccountLoading}=await server.ssrLoadModule('/src/components/AccountStates.jsx');
    const {default:Notice}=await server.ssrLoadModule('/src/components/ResultsNotice.jsx');
    const {FavoritesProvider}=await server.ssrLoadModule('/src/context/FavoritesContext.jsx');
    const {default:Results}=await server.ssrLoadModule('/src/pages/Results.jsx');
    const {default:SavedCard}=await server.ssrLoadModule('/src/components/SavedHotelCard.jsx');
    const {default:BookingForm}=await server.ssrLoadModule('/src/components/BookingForm.jsx');
    const {AuthView}=await server.ssrLoadModule('/src/components/AuthPage.jsx');
    const {SessionStatus}=await server.ssrLoadModule('/src/components/SessionBoundary.jsx');
    const {createAuthFormStore}=await server.ssrLoadModule('/src/services/authFormStore.js');
    const {createProfileStore}=await server.ssrLoadModule('/src/services/profileStore.js');
    const {createAccountListStore}=await server.ssrLoadModule('/src/services/accountListStore.js');
    const {readFavorites,toggleSavedFavorite}=await server.ssrLoadModule('/src/services/savedAccountData.js');
    const {createBookingHistory}=await server.ssrLoadModule('/src/services/bookingHistory.js');
    const {searchTours}=await server.ssrLoadModule('/src/services/tourService.js');
    const {createResultsSearch}=await server.ssrLoadModule('/src/services/resultsSearch.js');
    const {detailsError}=await server.ssrLoadModule('/src/utils/detailsPresentation.js');
    const {loadDetailsOffer}=await server.ssrLoadModule('/src/services/detailsOffer.js');
    const feedback=await server.ssrLoadModule('/src/utils/feedbackPresentation.js');
    const session=await server.ssrLoadModule('/src/services/session.js');
    const {HelpView}=await server.ssrLoadModule('/src/pages/Help.jsx');
    const {ContactsView}=await server.ssrLoadModule('/src/pages/Contacts.jsx');
    const login=()=>session.establishSession('offline-fixture',user,session.beginAuthAttempt());
    const profile=(api={})=>createProfileStore({token:'offline-fixture',api:{getProfile:async()=>user,updateProfile:async data=>({user:{...user,...data}}),...api},publish:()=>{}});
    const ph=s=>render(ProfileView,{state:s.getSnapshot(),actions:s});
    const fav=()=>createAccountListStore({ownerToken:'offline-fixture',readToken:()=>memory.get('token'),loadData:readFavorites});
    const fh=s=>render(FavoritesView,{status:s.getSnapshot().status,favorites:s.getSnapshot().items,pending:s.getSnapshot().pending,onRetry:s.load});
    const history=(api={getMyBookings:async()=>[]})=>createBookingHistory({token:'offline-fixture',userId:7,readUserId:()=>7,api});
    const bh=s=>render(MyBookingsView,{status:s.getSnapshot().status,bookings:s.getSnapshot().items,onRetry:s.load});
    login();
    for(const value of [undefined,'unknown','loading','invalid']) {
      await t.test(`Favorites ${String(value)} hides empty and stale records`,()=>{const html=render(FavoritesView,{status:value,favorites:[hotel]});assert.match(html,/Загружаем избранное/);assert.doesNotMatch(html,/Saved hotel|В избранном пока/);});
      await t.test(`Profile ${String(value)} hides stale identity and success`,()=>{const html=render(ProfileView,{state:{status:value,user,draft:{},message:poison},actions:{}});assert.match(html,/Загружаем профиль/);assert.doesNotMatch(html,/fixture@example/);safe(html);});
      await t.test(`BookingDetails ${String(value)} hides stale ready and unavailable`,()=>{const html=render(BookingDetailsView,{status:value,data:{booking:{id:1,hotel:poison}}});assert.match(html,/Загружаем заказ/);assert.doesNotMatch(html,/Запись не найдена/);safe(html);});
      await t.test(`MyBookings ${String(value)} never becomes empty`,()=>{const html=render(MyBookingsView,{status:value,bookings:[]});assert.match(html,/Загружаем бронирования/);assert.doesNotMatch(html,/У вас пока нет/);});
    }
    await t.test('Favorites guest has sign-in action without data',()=>{const html=render(FavoritesView,{status:'guest',favorites:[hotel]});assert.match(html,/Войти/);assert.doesNotMatch(html,/Saved hotel/);});
    await t.test('Favorites confirmed empty and ready are distinct',async()=>{body={success:true,data:[]};const s=fav();await s.load();assert.match(fh(s),/В избранном пока ничего нет/);body={success:true,data:[hotel]};await s.load();assert.match(fh(s),/Saved hotel/);});
    await t.test('Favorites failed load is safe error, never empty',async()=>{status=500;body={message:poison};const s=fav();await s.load();assert.match(fh(s),/Не удалось загрузить избранное/);assert.doesNotMatch(fh(s),/В избранном пока/);safe(fh(s));status=200;});
    for(const adding of [true,false]) await t.test(`Favorites ${adding?'add':'remove'} pending, duplicate guard, failed action truth`,async()=>{body={success:true,data:adding?[]:[hotel]};const s=fav();await s.load();status=500;body={message:poison};wait=deferred();const n=requests.length;const a=toggleSavedFavorite(s,hotel),b=toggleSavedFavorite(s,hotel);assert.deepEqual(s.getSnapshot().pending,['mock:11']);await Promise.resolve();assert.equal(requests.length,n+1);wait.resolve();wait=null;await Promise.all([assert.rejects(a),assert.rejects(b)]);assert.equal(s.getSnapshot().items.length,adding?0:1);assert.deepEqual(s.getSnapshot().pending,[]);status=200;});
    await t.test('Favorite removal has readable disabled busy control',()=>{const html=render(SavedCard,{item:hotel,pending:true});assert.match(html,/aria-busy="true"/);assert.match(html,/Удаление…/);assert.match(html,/disabled=""/);});
    await t.test('Profile saving precedes success and deduplicates',async()=>{const gate=deferred();let calls=0;const s=profile({updateProfile:async data=>{calls++;await gate.promise;return {user:{...user,...data}};}});await s.load();s.edit('full_name','Changed');const a=s.save();assert.equal(a,s.save());assert.match(ph(s),/aria-busy="true"/);assert.doesNotMatch(ph(s),/Изменения сохранены/);await Promise.resolve();assert.equal(calls,1);gate.resolve();await a;assert.match(ph(s),/Изменения сохранены/);});
    await t.test('Profile error preserves draft and clears on reset',async()=>{const s=profile({updateProfile:async()=>{throw Error(poison);}});await s.load();s.edit('full_name','Draft');await s.save();assert.match(ph(s),/Не удалось сохранить изменения/);safe(ph(s));assert.equal(s.getSnapshot().draft.full_name,'Draft');s.cancel();assert.equal(s.getSnapshot().draft.full_name,user.full_name);assert.equal(s.getSnapshot().saveError,'');});
    await t.test('Profile invalidation clears success error and password feedback',async()=>{const s=profile();await s.load();s.edit('full_name','Saved');await s.save();s.editPassword('currentPassword','synthetic-password');s.invalidate();assert.equal(s.getSnapshot().message,'');assert.equal(s.getSnapshot().saveError,'');assert.equal(s.getSnapshot().password.currentPassword,'');assert.equal(s.getSnapshot().passwordMessage,'');assert.equal(s.getSnapshot().user,null);});
    await t.test('Profile password form pending isolated from profile save',async()=>{const s=profile();await s.load();const state={...s.getSnapshot(),passwordBusy:true};const html=render(ProfileView,{state,actions:s});assert.match(html,/Безопасность[\s\S]*aria-busy="true"/);assert.match(html,/Личные данные[\s\S]*aria-busy="false"/);});
    await t.test('Profile notification preferences do not promise delivery',async()=>{const s=profile();await s.load();const html=ph(s);assert.match(html,/Предпочтения сохраняются в аккаунте/);assert.match(html,/после запуска сервиса/);assert.doesNotMatch(html,/Мы отправим|Вы будете получать/);});
    await t.test('MyBookings load confirmed [] renders empty',async()=>{const h=history();assert.match(bh(h.list),/Загружаем/);await h.ensureListLoaded();assert.match(bh(h.list),/У вас пока нет бронирований/);});
    await t.test('MyBookings error waits for explicit retry and deduplicates',async()=>{let calls=0;const h=history({getMyBookings:async()=>{calls++;throw Error(poison);}});await h.ensureListLoaded();safe(bh(h.list));assert.match(bh(h.list),/Не удалось загрузить бронирования/);assert.doesNotMatch(bh(h.list),/У вас пока нет/);await h.ensureListLoaded();assert.equal(calls,1);const a=h.list.load();assert.equal(a,h.list.load());await a;assert.equal(calls,2);});
    await t.test('MyBookings late prior response cannot survive invalidation',async()=>{const gate=deferred();const h=history({getMyBookings:()=>gate.promise});const a=h.list.load();await Promise.resolve();h.invalidate();gate.resolve([]);await a;assert.equal(h.list.getSnapshot().status,'loading');assert.doesNotMatch(bh(h.list),/У вас пока нет/);});
    await t.test('BookingDetails error is safe and unavailable has back link',()=>{const html=render(BookingDetailsView,{status:'error',data:{booking:{id:1,hotel:poison}},onRetry:()=>{}});safe(html);assert.match(html,/Не удалось открыть заказ/);const missing=render(BookingDetailsView,{status:'ready',data:{notFound:true}});assert.match(missing,/Запись не найдена или недоступна/);assert.match(missing,/href="\/my-bookings"/);});
    await t.test('Account error keyboard retry only on user action',()=>{let calls=0;const tree=AccountError({title:'Не удалось выполнить действие',onRetry:()=>calls++});assert.equal(calls,0);const button=tree.props.children.find(x=>x?.type==='button');assert.equal(button.props.type,'button');button.props.onClick();assert.equal(calls,1);assert.match(render(AccountError,{title:'Ошибка'}),/disabled=""/);});
    await t.test('Account loading status and error alert have distinct semantics',()=>{assert.match(render(AccountLoading,{label:'Загрузка'}),/role="status"/);assert.match(render(AccountError,{title:'Ошибка'}),/role="alert"/);});
    const params=new URLSearchParams('provider=hotelbeds&countryCode=TR&destinationCode=AYT&checkIn=2035-10-05&nights=7&adults=2&children=0&rooms=1');
    for(const [state,pattern] of [['PROVIDER_EMPTY',/По вашему запросу отели не найдены/],['FILTER_EMPTY',/По заданным фильтрам ничего не найдено/],['ERROR',/Не удалось выполнить поиск/]]) await t.test(`Results ${state} fixed safe feedback`,()=>{const html=render(Notice,{state,params,error:Error(poison),onRetry:()=>{},onReset:()=>{}});assert.match(html,pattern);safe(html);});
    await t.test('Results unknown notice never claims empty',()=>assert.equal(render(Notice,{state:'unknown',params}),''));
    await t.test('Results stale refresh remains explicit',()=>{let calls=0;const props={state:'ERROR',stale:true,params,onRetry:()=>calls++};assert.match(render(Notice,props),/Обновить результаты/);assert.equal(calls,0);Notice(props).props.children.find(x=>x?.type==='button').props.onClick();assert.equal(calls,1);});
    await t.test('Results initial page renders loading skeleton before any request',()=>{const n=requests.length;const html=renderToStaticMarkup(React.createElement(MemoryRouter,{initialEntries:['/results?'+params]},React.createElement(FavoritesProvider,{},React.createElement(Results))));assert.match(html,/data-search-state="LOADING"/);assert.match(html,/class="result-skeleton"/);assert.doesNotMatch(html,/По вашему запросу отели не найдены/);assert.equal(requests.length,n);});
    for(const invalid of [null,{}, {data:null},{data:{}}]) await t.test(`malformed search ${JSON.stringify(invalid)} is not empty`,async()=>{body=invalid;await assert.rejects(searchTours({}),/INVALID_SEARCH_RESPONSE/);});
    await t.test('confirmed search [] stays valid',async()=>{body={data:[]};assert.deepEqual((await searchTours({})).data,[]);});
    await t.test('search failure never automatically retries',async()=>{let calls=0;const load=createResultsSearch(async()=>{calls++;throw Error(poison);});const key=JSON.stringify(Object.fromEntries(params));await assert.rejects(load(key));await assert.rejects(load(key));assert.equal(calls,1);await assert.rejects(load(key,{retry:true}));assert.equal(calls,2);});
    await t.test('Details unknown and stale error copies exclude raw data',()=>{safe(JSON.stringify(detailsError(Error(poison))));assert.match(JSON.stringify(detailsError({code:'SELECTED_OFFER_STALE',message:poison})),/устарел/);});
    await t.test('Details stale selected offer cannot refetch provider',async()=>{const n=requests.length;await assert.rejects(loadDetailsOffer({selectedOffer:{provider:'hotelbeds',providerHotelId:'11',observedAt:'2000-01-01'},provider:'hotelbeds',id:'11',search:''}));assert.equal(requests.length,n);});
    for(const mode of ['login','register']) await t.test(`${mode} pending duplicate submit and safe failure`,async()=>{session.logout();const s=createAuthFormStore({mode,onSuccess:()=>assert.fail('failed request cannot succeed')});for(const [k,v] of Object.entries({email:'fixture@example.test',password:'synthetic-password',full_name:'Fixture',confirmPassword:'synthetic-password'}))s.edit(k,v);status=500;body={message:poison};wait=deferred();const n=requests.length;const a=s.submit();assert.equal(a,s.submit());assert.match(render(AuthView,{mode,state:s.getSnapshot(),actions:s}),/aria-busy="true"/);await Promise.resolve();assert.equal(requests.length,n+1);wait.resolve();wait=null;await a;const html=render(AuthView,{mode,state:s.getSnapshot(),actions:s});safe(html);assert.doesNotMatch(html,/synthetic-password/);assert.match(html,/role="alert"/);status=200;});
    await t.test('logout clears connected auth feedback',async()=>{const s=createAuthFormStore({mode:'login',onSuccess:()=>{}});const stop=s.connect();s.edit('email','invalid');await s.submit();assert.ok(Object.keys(s.getSnapshot().errors).length);session.logout();assert.deepEqual(s.getSnapshot().errors,{});assert.equal(s.getSnapshot().error,'');stop();});
    await t.test('expired session notice is fixed public text',()=>{login();session.clearSession('offline-fixture','expired');assert.equal(session.validatedSessionSnapshot().notice,'Сессия завершена. Войдите снова.');safe(session.validatedSessionSnapshot().notice);});
    await t.test('bootstrap unknown status and error remain distinct',()=>{assert.match(render(SessionStatus,{status:'unknown'}),/role="status"/);assert.match(render(SessionStatus,{status:'error'}),/role="alert"/);});
    for(const code of [undefined,'UNKNOWN','__proto__','constructor','HOTELBEDS_RATE_EXPIRED','HOTELBEDS_CONFIRMATION_UNKNOWN','HOTELBEDS_AT_HOTEL_UNSUPPORTED']) await t.test(`Checkout fixed copy for ${String(code)}`,()=>{const message=feedback.checkoutFailureMessage(code);assert.equal(typeof message,'string');safe(message);assert.doesNotMatch(message,/\?{3}/);if(code==='HOTELBEDS_CONFIRMATION_UNKNOWN')assert.match(message,/не повторяйте/);});
    for(const file of ['pages/Checkout.jsx','components/checkout/ReviewStep.jsx','pages/Voucher.jsx']) await t.test(`${file} no raw error UI or payload logging`,async()=>{const text=await source(file);assert.doesNotMatch(text,/err(?:or)?\??\.message|console\.(error|log)|JSON.stringify/);assert.match(text,/feedbackPresentation/);});
    await t.test('Voucher fixed failure and duplicate PDF guard without executing endpoint',async()=>{safe(feedback.voucherFailureMessage);safe(feedback.pdfFailureMessage);const text=await source('pages/Voucher.jsx');assert.match(text,/if \(downloadLock.current\) return/);assert.match(text,/setDownloadError\(pdfFailureMessage\)/);assert.match(text,/role="alert"/);assert.match(text,/aria-busy=\{downloading\}/);});
    await t.test('BookingForm is truthful disabled placeholder with no collected personal data',()=>{const html=render(BookingForm);assert.match(html,/Заявки не отправляются/);assert.match(html,/disabled=""/);assert.doesNotMatch(html,/успешно отправлена|<input|<form/);});
    await t.test('Help and Contacts have no pretend submission or changed contact actions',()=>{const html=render(HelpView)+render(ContactsView);assert.match(html,/href="mailto:/);assert.match(html,/href="tel:/);assert.doesNotMatch(html,/<form|отправлено|сообщение отправлено/i);});
    await t.test('Header has favorites and account controls, no fake notification center',async()=>{const text=await source('components/Navbar.jsx');assert.match(text,/favorites/);assert.match(text,/onClick=\{logout\}/);assert.doesNotMatch(text,/notification|bell|уведомлен/i);});
    for(const width of [320,390,768,1440]) await t.test(`feedback CSS contracts at ${width}, not browser measurement`,async()=>{const files=['styles/AccountPages.css','styles/Auth.css','styles/Profile.css','styles/Checkout.css','styles/Voucher.css','styles/Results.css'];for(const f of files){const css=await source(f);assert.doesNotThrow(()=>postcss.parse(css));assert.match(css,/overflow-wrap\s*:\s*anywhere/);}const v=await source('styles/Voucher.css');assert.match(v,/flex-wrap:wrap/);assert.match(v,/:focus-visible/);assert.match(await source('styles/AccountPages.css'),/max-width:600px/);});
    await t.test('consumer failure output never interpolates raw errors',async()=>{for(const f of ['components/AuthPage.jsx','pages/Profile.jsx','pages/Favorites.jsx','pages/MyBookings.jsx','pages/BookingDetails.jsx','pages/TourDetails.jsx','pages/Results.jsx'])assert.doesNotMatch(await source(f),/\{\s*(?:error|err)\??\.message\s*\}|alert\((?:error|err)/);});
    await t.test('successful favorite mutation updates only after confirmation',async()=>{login();body={success:true,data:[]};const s=fav();await s.load();body={success:true,data:hotel};wait=deferred();const op=toggleSavedFavorite(s,hotel);assert.equal(s.getSnapshot().items.length,0);await Promise.resolve();wait.resolve();wait=null;await op;assert.equal(s.getSnapshot().items.length,1);});
    await t.test('profile connected logout clears prior success before next account',async()=>{login();const s=profile();const stop=s.connect();await s.load();s.edit('full_name','Saved');await s.save();assert.ok(s.getSnapshot().message);session.logout();assert.equal(s.getSnapshot().message,'');assert.equal(s.getSnapshot().user,null);session.establishSession('offline-second',{...user,id:8},session.beginAuthAttempt());assert.equal(s.getSnapshot().user,null);stop();});
    await t.test('registration conflict has intentional safe copy',async()=>{session.logout();const s=createAuthFormStore({mode:'register',onSuccess:()=>assert.fail('conflict')});for(const [k,v] of Object.entries({email:'fixture@example.test',password:'synthetic-password',full_name:'Fixture',confirmPassword:'synthetic-password'}))s.edit(k,v);status=409;body={message:poison};await s.submit();const html=render(AuthView,{mode:'register',state:s.getSnapshot(),actions:s});assert.match(html,/Аккаунт с таким email уже существует/);safe(html);assert.doesNotMatch(html,/synthetic-password/);status=200;});
    await t.test('all exercised network requests are intercepted own API only, zero provider calls',()=>{assert.ok(requests.length>0);assert.ok(requests.every(([path])=>!/(hotelbeds|checkrate|cancellation|payment|voucher|checkout)/i.test(path)));});
  } finally {globalThis.localStorage=previous.storage;globalThis.window=previous.window;await server.close();}
});
